# ################################
# Model: Speaker Verification Baseline
# Authors: Hwidong Na 2020
#          Mirco Ravanelli 2020
#          Francesco Nespoli 2023
# ################################

seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
data_folder_tr: /home/francesco/Documents/Python_Project/VoicePrivacy/speaker-anonymization/Voice-Privacy-Challenge-2022/baseline/corpora
data_folder_test: /home/francesco/Documents/Python_Project/VoicePrivacy/speaker-anonymization/Voice-Privacy-Challenge-2022/baseline
output_folder: /home/francesco/Documents/Python_Project/Collaborations/Joerg/speechbrain_privacy/custom_training/ASV/testing_scripts/run_plda_verification/results/libri_dev_trials_f
save_folder: !ref <output_folder>/save/
device: 'cuda:0'

# Use the following links for the official voxceleb splits:
# VoxCeleb1 (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt
# VoxCeleb1-H (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_hard2.txt
# VoxCeleb1-E (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_all2.txt.
# VoxCeleb1-E and VoxCeleb1-H lists are drawn from the VoxCeleb1 training set.
# Therefore you cannot use any files in VoxCeleb1 for training if you are using these lists for testing.
verification_file: /home/francesco/Documents/Python_Project/Collaborations/Joerg/speechbrain_privacy/custom_training/ASV/testing_scripts/trials_files/libri_dev_trials_f/trials

# Here, the pretrained embedding model trained with train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml
# is downloaded from the speechbrain HuggingFace repository.
# However, a local path pointing to a directory containing your checkpoints may also be specified
# instead (see pretrainer below)
pretrain_path: speechbrain/spkrec-ecapa-voxceleb

# csv files
train_data: /home/francesco/Documents/Python_Project/Collaborations/Joerg/speechbrain_privacy/custom_training/ASV/testing_scripts/generate_plda_datamanifest/librispeech_360_clean.json
enrol_data: /home/francesco/Documents/Python_Project/Collaborations/Joerg/speechbrain_privacy/custom_training/ASV/testing_scripts/generate_plda_datamanifest/clean_datamanifests/libri_dev_enrolls.json
test_data:  /home/francesco/Documents/Python_Project/Collaborations/Joerg/speechbrain_privacy/custom_training/ASV/testing_scripts/generate_plda_datamanifest/clean_datamanifests/libri_dev_trials_f.json

batch_size: 8
#score_norm: s-norm  # z-norm t-norm s-norm (uncomment to enable it)
cohort_size: 20000 # amount of imposter utterances in normalization cohort
n_train_snts: 400000 # used for normalization stats

# Feature parameters
n_mels: 80
# left_frames: 0
# right_frames: 0
# deltas: False

# Separator for correct data splitting
separator: "-"

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

enrol_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <n_mels>
    channels: [1024, 1024, 1024, 1024, 3072]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    attention_channels: 128
    lin_neurons: 192

compute_plda: !new:speechbrain.processing.PLDA_LDA.PLDA
    rank_f: 100
    nb_iter: 10
    scaling_factor: 0.05

emb_dim: 192

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        embedding_model: !ref <embedding_model>
    paths:
        embedding_model: !ref <pretrain_path>/embedding_model.ckpt
