# ################################
# Model: Speaker Verification Baseline using PLDA
# Authors: Nauman Dawalatabad & Mirco Ravanelli 2020
#          Francesco Nespoli 2023
#          Jule Pohlhausen 2023
# ################################

seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
data_folder_tr: !PLACEHOLDER #e.g., /localscratch/librispeech-360
data_folder_test: !PLACEHOLDER #e.g., /localscratch/voxceleb1_2
subset: !PLACEHOLDER #e.g., libri_dev_trials_f
subset_enrol: !PLACEHOLDER #e.g., libri_dev_enrolls
output_folder: !ref results/voxceleb1_2/speaker_verification_xvectors/<subset>
save_folder: !ref <output_folder>/save/
device: 'cuda:0'

# Define verification file
verification_file: !ref ../trials_files/<subset>/trials

# Here, the pretrained embedding model trained with train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml
# is downloaded from the speechbrain HuggingFace repository.
# However, a local path pointing to a directory containing your checkpoints may also be specified
# instead (see pretrainer below)
pretrain_path: speechbrain/spkrec-xvect-voxceleb

# json files
json_folder: !PLACEHOLDER #e.g., /localscratch/generate_plda_datamanifest/jsons
train_data: !ref <json_folder>/librispeech_360_clean.json
enrol_data: !ref <json_folder>/<subset_enrol>.json
test_data:  !ref <json_folder>/<subset>.json

split_ratio: [90, 10]
seg_dur: 3
skip_prep: False

batch_size: 128
n_train_snts: 104014 # used for normalization stats

# Separator for correct data splitting
separator: "-"

# Feature parameters
n_mels: 80
emb_dim: 512
rank_f: 100

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

enrol_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

# Model params
compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

embedding_model: !new:speechbrain.lobes.models.Xvector.Xvector
    in_channels: !ref <n_mels>
    activation: !name:torch.nn.LeakyReLU
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: !ref <emb_dim>

compute_plda: !new:speechbrain.processing.PLDA_LDA.PLDA
    rank_f: !ref <rank_f>
    nb_iter: 1
    scaling_factor: 0.1

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        embedding_model: !ref <embedding_model>
    paths:
        embedding_model: !ref <pretrain_path>/embedding_model.ckpt